### PR TITLE
Added unit tests and an assert to cover a bounds error on small examples

### PR DESCRIPTION
**Pull request by slundberg**
This adds Travis unit tests for the hclust implementation, and also an assert that more than 3 variables are being clustered since the current algorithm assumes that.

I also updated a tuple type annotation in kmedoids.jl to address a Travis error in v0.4

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Thanks!

**Comment by slundberg** [comment]
Sure! Would it be possible to bump the released Clustering version to include these updates?

**Comment by johnmyleswhite** [comment]
Sure. Feel free to make a request on METADATA and I'll rubberstamp it.

**Comment by slundberg** [comment]
I would be glad to do that, however I am having some issues. In the online
docs it says "The Pkg.publish() command will fork the METADATA repository
on GitHub, push your changes to your fork, and open a pull request"

However, when I try after tagging the Clustering checkout I get "ERROR:
Permission to JuliaStats/Clustering.jl.git denied to slundberg."

Can you point me to the right next step?

**Comment by johnmyleswhite** [comment]
I would circumvent `Pkg.publish` and just publish a PR to the METADATA repository that updates the raw data. The data format is pretty easy to understand: you create a directory with some files, one of which includes the SHA1 of the commit you want to tag.

**Comment by slundberg** [comment]
Great. Done.

**Comment by johnmyleswhite** [comment]
Thanks!

**Pull request merged**
