### PR TITLE
Assigning  "pairwise" in procedure kmeans.jl

### PR DESCRIPTION
**Pull request by tangwang-USTC**
Dear all,
I recently tried to perform `clustering.jl`  in module `BasisFunctionExpansions.jl`. Unfortunately, I find out that 
both module `Distance.jl` and `StatsBase.jl` export "pairwise", uses of it in procedure "kmeans.jl" and "seeding.jl" must be qualified (see issues 235 which also is a question to wildart).  It is not conviennient to use `clustering.jl`.
Can you check this problem?

Best wishes!

Tangwang

### CODE REVIEW

**Comment by wildart** [comment]
You are doing something wrong. There is no exporting conflict with `pairwise` function. It was resolved about two years ago by adding an original `pairwise` definition to StatsAPI package which is a dependency for both Distances & StatsBase, see here https://github.com/JuliaStats/StatsAPI.jl/blob/14e0ba729d08d771c462b1c494d81462961d7745/src/StatsAPI.jl#L17-L24.

Try to update your packages to the recent versions that may resolve you problem.

**Comment by alyst** [comment]
There's something wrong with this PR, you want to push the whole *Clustering.jl* history.
I will close it, let's continue the discussion and clarify the issues that you have in #235.

**Comment by tangwang-USTC** [comment]
Dear All:


&nbsp; I am really grateful to receive your help. I will check my procedure again.


&nbsp; Thank you much again!
&nbsp;
&nbsp; Best wishes!


Tangwang




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月22日(星期六) 中午12:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JuliaStats/Clustering.jl] Assigning  &quot;pairwise&quot; in procedure kmeans.jl (PR #237)





 
You are doing something wrong. There is no exporting conflict with pairwise function. It was resolved about two years ago by adding an original pairwise definition to StatsAPI package which is a dependency for both Distances &amp; StatsBase, see here https://github.com/JuliaStats/StatsAPI.jl/blob/14e0ba729d08d771c462b1c494d81462961d7745/src/StatsAPI.jl#L17-L24.
 
Try to update your packages to the recent versions that may resolve you problem.

**Comment by tangwang-USTC** [comment]
Dear All,


&nbsp; I am sorry that I had not find the record two year ago.&nbsp;
&nbsp; Maybe it is owing to my verision of Julia is not the lastest one and leads to some conflict.&nbsp;
&nbsp; I will update my verision and environment according to your advise.


Thank you very much!


Best wish!






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexey ***@***.***&gt;; 
发送时间: 2022年10月22日(星期六) 中午12:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JuliaStats/Clustering.jl] Assigning  &quot;pairwise&quot; in procedure kmeans.jl (PR #237)





 
There's something wrong with this PR, you want to push the whole Clustering.jl history.
 I will close it, let's continue the discussion and clarify the issues that you have in #235.

**Pull request closed without merging**
