### PR TITLE
Refactor kmedoids assignment update

### PR DESCRIPTION
**Pull request by juliohm**
Replace the search by an explicit call to `findmin()`. Although simple, this change makes the code easier to read by future contributors.

### CODE REVIEW

**Comment by lindahua** [comment]
You may want to use ``sub`` instead of the bracket operators to get a slice, otherwise it would lead to unnecessary memory allocation and copying.

**Comment by juliohm** [comment]
@lindahua done, thanks for the suggestion.

**Comment by juliohm** [comment]
@lindahua is this pull request ready to be merged?

**Comment by juliohm** [comment]
Should I close this pull request? Not interested?

**Comment by juliohm** [comment]
Can anyone please take a look at this simple refactoring of the code?

**Comment by juliohm** [comment]
@timholy do you have write access on this repo? Are you ok with this trivial change?

**Comment by timholy** [comment]
No, I don't have merge privileges.

**Comment by juliohm** [comment]
Thanks Tim, I will wait for 1 more month and close it if no one replies.

**Comment by kmsquire** [comment]
Will merge after CI runs.  Sorry for the lack of response--I don't usually follow this repo, and only noticed the change because you closed it!

**Comment by kmsquire** [comment]
It seems that this patch has a problem on Julia v0.3.

```julia
ERROR: `sub` has no method matching sub(::Array{Float64,2}, ::Array{Int64,1}, ::Int64)
 in _kmed_update_assignments! at /home/travis/.julia/v0.3/Clustering/src/kmedoids.jl:155
 in _kmedoids! at /home/travis/.julia/v0.3/Clustering/src/kmedoids.jl:83
 in kmedoids at /home/travis/.julia/v0.3/Clustering/src/kmedoids.jl:39
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in anonymous at no file:17
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
```

**Comment by juliohm** [comment]
Hi @kmsquire , thanks for the reply. If `Julia v0.3` is to be supported by the package, then I think this pull request should be closed. Do you agree?

**Comment by kmsquire** [comment]
Since there are so few people actively maintaining the package, I would be okay with dropping support for v0.4.

@lindahua @johnmyleswhite Thoughts, if you're available?

**Comment by juliohm** [comment]
@kmsquire this pull request is hanging out for a while, I don't think it is useful, will just close it. Thank you for your support!

**Comment by kmsquire** [comment]
@juliohm, sorry, I don't look at this package very frequently. If I get the chance, I'll look at it soon, reopen, and merge.

**Pull request closed without merging**
