### PR TITLE
remove deprecated warnings

### LINKED ISSUE #53: Warnings with Julia v"0.4.0"
I'm seeing quite a few warnings from Clustering.jl on Julia 0.4.0

e.g.

```
WARNING: [a] concatenation is deprecated; use collect(a) instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at ./abstractarray.jl:29
 in hclust at /home/jeff/.julia/v0.4/Clustering/src/hclust.jl:334
 in hclust at /home/jeff/.julia/v0.4/Clustering/src/hclust.jl:342
 [inlined code] from /home/jeff/.julia/v0.4/Clustering/test/hclust.jl:7
 in anonymous at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from /home/jeff/.julia/v0.4/Clustering/test/runtests.jl:15
 in anonymous at no file:14
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/jeff/.julia/v0.4/Clustering/test/hclust.jl, in expression starting on line 6
```

and 

```
WARNING: int(x) is deprecated, use Int(x) instead.
 in depwarn at deprecated.jl:73
 in int at deprecated.jl:50
 in kmeans! at /home/jeff/.julia/v0.4/Clustering/src/kmeans.jl:37
 in kmeans at /home/jeff/.julia/v0.4/Clustering/src/kmeans.jl:53
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from /home/jeff/.julia/v0.4/Clustering/test/runtests.jl:15
 in anonymous at no file:14
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/jeff/.julia/v0.4/Clustering/test/kmeans.jl, in expression starting on line 15
```

and

```
WARNING: deprecated syntax "{a=>b, ...}" at /home/jeff/.julia/v0.4/Clustering/test/hclust_generated_examples.jl:558.
Use "Dict{Any,Any}(a=>b, ...)" instead.
```

I think these come warnings from changes to the Julia language that appeared around the time of the release candidates. I'm using version 0.4.0 of Clustering.jl, but I get the warnings when I checkout master too.

### PR DESCRIPTION
**Pull request by jeff-regier**
Hi @johnmyleswhite , This PR fixes warnings from Julia 0.4 while maintaining compatibility with Julia v0.3 . It closes #53. All the commits have been squashed together.

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Will merge once Travis approves.

**Comment by johnmyleswhite** [comment]
Failed on OS X, but for reasons that I think can be ignored given that the code seems to be correct.

**Comment by johnmyleswhite** [comment]
Thanks for doing this!

**Comment by jeff-regier** [comment]
Sure! Will you tag a new version of Clustering.jl with these changes?

**Pull request merged**
