### PR TITLE
pairwise quick fix

### PR DESCRIPTION
**Pull request by guo-yong-zhi**

### CODE REVIEW

**Comment by alyst** [comment]
The tests work for me with up-to-date versions of the dependencies.
If you still observe the bug #217 on your configuration, could you please provide the details (Julia version and `Pkg.status()`)?

**Comment by guo-yong-zhi** [comment]
I still have the problem of `both StatsBase and Distances export "pairwise"` after `Pkg.update()`. Here are some information about my env.
>Status `~/.julia/environments/v1.6/Project.toml`
  [6e4b80f9] BenchmarkTools v1.1.1
  [336ed68f] CSV v0.8.5
  [aaaa29a8] Clustering v0.14.2
  [8f4d0f93] Conda v1.5.2
  [a93c6f00] DataFrames v1.2.2
  [c5bfea45] Embeddings v0.4.1
  [cd3eb016] HTTP v0.9.13
  [7073ff75] IJulia v1.23.2
  [916415d5] Images v0.24.1
  [ae8d54c2] Luxor v2.14.0
  [91a5bcdd] Plots v1.19.4
  [c3e4b0f8] Pluto v0.15.1
  [438e738f] PyCall v1.92.3
  [295af30f] Revise v3.1.17
  [24678dba] TSne v1.2.0


>`versioninfo()`
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

>`Manifest.toml`
[[StatsBase]]
deps = ["DataAPI", "DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "StatsAPI"]
git-tree-sha1 = "fed1ec1e65749c4d96fc20dd13bea72b55457e62"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.33.9"
[[Distances]]
deps = ["LinearAlgebra", "Statistics"]
git-tree-sha1 = "a5b88815e6984e9f3256b6ca0dc63109b16a506f"
uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
version = "0.9.2"

**Comment by alyst** [comment]
Thank you for the info! It looks like at least tsne.jl in your setup is holding back the update of Distances.jl to 0.10, but it's nothing to do with Clustering.jl, so I'll close this PR.

**Comment by guo-yong-zhi** [comment]
Maybe you can remove [the compatibility statement](https://github.com/JuliaStats/Clustering.jl/blob/8af2507d44745bb1a3cec4b8d03918d17082a381/Project.toml#L15)  for Distances.jl 0.9.

**Comment by alyst** [comment]
Clustering was working with Distances 0.9, it's the combination of the other packages that breaks it.
Anyway, I think it would not help in your situation - it will just make Pkg.update() fail to resolve the valid Distances.jl version.

**Comment by guo-yong-zhi** [comment]
> Clustering was working with Distances 0.9, it's the combination of the other packages that breaks it. 

I don't think so. I tried with this code:
```julia
using Pkg
Pkg.activate("test_clustering")
Pkg.add(name="Distances", version="0.9.2")
Pkg.pin("Distances")
Pkg.add(name="Clustering")

using Clustering
X = rand(5, 1000)
R = kmeans(X, 20; maxiter=200, display=:iter)
```
And the bug comes:
>WARNING: both StatsBase and Distances export "pairwise"; uses of it in module Clustering must be qualified
WARNING: both StatsBase and Distances export "pairwise!"; uses of it in module Clustering must be qualified

I know it doesn't help in my situation, but the Clustering is really NOT compatible with Distances 0.9.

**Comment by alyst** [comment]
Thank you for your investigation. As I said, there are other packages that were updated (at least StatsBase, StatAPI), so just downgrading Distances would not help.
Eventually we would drop 0.9 support, but right now there are no other changes in Clustering.jl that would require releasing the new version.
And it would not fix your case, because you will have a conflict with TSne.jl requiring 0.9 and Clustering.jl would require 0.10.

Right now I'm working on updating TSne.jl to use Distances 0.10. Once it will be updated (in a couple of hours), your issue would be solved.

**Comment by guo-yong-zhi** [comment]
Thank you for your explanation. Thank you for your great work.

**Comment by alyst** [comment]
@guo-yong-zhi TSne.jl v1.3.0 is released. When you update the packages, Distances.jl (don't forget to unpin it) should be updated to 0.10. Let me know if you will still have troubles.

**Pull request closed without merging**
