### PR TITLE
Bump Distances.jl

### PR DESCRIPTION
**Pull request by juliohm**
Bump Distances.jl to 0.10

### CODE REVIEW

**Comment by juliohm** [comment]
Could you please merge and tag a new release? The Travis error should be unrelated.

**Comment by ablaom** [comment]
ping @alyst

**Comment by juliohm** [comment]
This PR is holding a set of releases downstream, and it is really difficult to depend on it when no one from JuliaStats is watching. How can we solve this problem? Can someone please merge this or make me a member of the org so that I can help?

cc: @dkarrasch @nalimilan

**Comment by nalimilan** [comment]
It's annoying that tests fail on Julia 1.5, but since they already failed on master and still pass on 1.0 I guess the problem is unrelated to Distances 0.10.

**Comment by nalimilan** [comment]
https://github.com/JuliaRegistries/General/pull/23172

**Comment by juliohm** [comment]
Yes, the tests are failing because of changes in the RNG in newer versions
of Julia. The problem is in the test itself uses random numbers.

Appreciate if you can trigger JuliaRegistrator.

Em dom., 18 de out. de 2020 às 08:27, Milan Bouchet-Valat <
notifications@github.com> escreveu:

**Pull request merged**
