### PR TITLE
Support AbstractMatrix in fuzzy_cmeans

### PR DESCRIPTION
**Pull request by timholy**
The same change could be made in many other methods (looks like this package has lots of legacy code), but at least this is a step in the right direction.

### CODE REVIEW

**Comment by timholy** [comment]
This also adds a convenient `show` method which can be used in doctests.

**Comment by alyst** [comment]
Thanks! Could you please modify the `show()` method to report the number of iterations also when there's no convergence?

**Comment by timholy** [comment]
Done

**Comment by timholy** [comment]
Thanks!

I know it's a trivial change, but could you tag `v0.12.1`? ImageSegmentation needs this feature.

**Comment by alyst** [comment]
v0.12.1 should be in the registry now.

**Pull request merged**
